export const texts = {
    title: "Haciendo \nMatch entre \nPersonas y \nMascotas",
    subtitle: "En Pawify, creemos que cada animal \nmerece un hogar lleno de amor",
    adoptionTitle: "Adopta ahora",
    freeServiceTitle: "El servicio es \ncompletamente \ngratuito y \nsiempre lo será.",
    freeServiceText: "No aceptamos ni solicitamos dinero por ningún animal.",
    shelterTitle: "Si eres un refugio o \nasociación, publica tus \nmascotas🐾",
    shelterText: "¡Publica una mascota en busca \nde un hogar! Le daremos \nvisibilidad.",
    lookingForPetTitle: "Si estás buscando \nadoptar has llegado al \nlugar adecuado❤️",
    lookingForPetText: "Encuentra la mascota perfecta \ncerca de tu ubicación para \nadoptar.",
    adoptedPetsNumber: "347+",
    adoptedPetsText: "Mascotas adoptadas",
    adoptedPetsDescription: "Con Pawify, hemos ayudado a dar visibilidad a peluditos en busca de un hogar en todo el mundo.",
    dailyUsersNumber: "14k+",
    dailyUsersText: "Usuarios diarios en busca de adopción",
    dailyUserDescription: "Utilizamos marketing digital para llegar a todos los que buscan peluditos para adoptar.",
    titleTwo: "Tenemos la compañía que estabas buscando, esperando ser adoptada.",
    subtitleTwo: "Ponte en contacto con el dueño o refugio que los tiene esperándote.",
    serviceSection: "Nuestro Servicio",
    serviceTitle: "Somos la solución para todos los peluditos que esperan ser adoptados.",
    // serviceSubtitle: "Somos el nuevo buscador para <b>mascotas invisibles</b> en todo el mundo, ayudándolas a encontrar un hogar lo antes posible.",
    serviceOne: "Cuidado y Estilismo",
    serviceOneDescription: "Consiente a tu mascota con los mejores servicios de cuidado y estilismo. Encuentra baños, cortes de pelo, recorte de uñas y más con peluqueros de confianza cerca de ti.",
    serviceTwo: "Entrenamiento para Mascotas",
    serviceTwoDescription: "Conéctate con entrenadores expertos para el adiestramiento en obediencia y la modificación de conducta. Ayuda a tu mascota a aprender buenos modales y nuevas habilidades.",
    serviceThree: "Adopciones",
    serviceThreeDescription: "Adopta un peludito que lo necesita. Explora los listados de mascotas que esperan un hogar lleno de amor. Comienza hoy tu viaje de adopción.",
    serviceFour: "Cuidado de Mascotas",
    serviceFourDescription: "Mantén a tu mascota sana con nuestros servicios de cuidado. Encuentra veterinarios, vacunas y chequeos de bienestar con proveedores de confianza. 🏥",
    serviceFive: "Accesorios con Estilo para tu Peludo",
    serviceFiveDescription: "Descubre accesorios a la moda para tu mascota. Compra collares elegantes, correas con estilo y artículos únicos para que tu peludito destaque.",
    serviceSix: "Tienda para Mascotas 🛒​",
    serviceSixDescription: "Consigue todo lo que tu mascota necesita en un solo lugar. Compra comida, juguetes, camas y mucho más para tu peludito en nuestra tienda para mascotas.",
    proximamente: "Próximamente 🚀",
    whySection: "¿Por qué elegir Pawify?",
    whyTitle: "La Plataforma Definitiva para la Adopción y el Cuidado de Mascotas en Todo el Mundo",
    whySubtitle: "Utilizamos marketing digital para aumentar la visibilidad de mascotas y servicios de cuidado en todo el mundo, ayudándolos a encontrar hogares más rápido.",
    reasonOne: "Encuentra tu Peludito",
    reasonOneDescription: "Nuestra plataforma fácil de usar te ayuda a encontrar el compañero perfecto que espera un hogar lleno de amor. Comienza hoy tu viaje de adopción.",
    reasonTwo: "Socios Certificados",
    reasonTwoDescription: "Encuentra socios certificados y de confianza para todas las necesidades de tu mascota.",
    reasonThree: "Ponte en Contacto",
    reasonThreeDescription: "Contacta directamente con nuestros socios certificados para conectar con el peludito que amas o encontrar el servicio que necesitas",
    reasonFour: "Soporte Premium 24/7",
    reasonFourDescription: "Disfruta de tranquilidad total con nuestro soporte premium 24/7.",
    reasonFourDescriptionLink: " Info@pawify.org",
    moreSection: "Descubre más",
    moreTitle: "Todo lo que tu Mascota Necesita, en un Solo Lugar",
    // moreSubtitle: "Descubre una amplia gama de servicios y productos diseñados para cubrir todas las necesidades de tu mascota.",
    moreInfoOne: "Tienda de Mascotas",
    moreInfoOneDescription: "Consigue todo lo esencial para tu mascota en un solo lugar. Compra comida, juguetes, camas y mucho más para tu peludito en nuestra tienda para mascotas.",
    moreInfoTwo: "Cuidado de Mascotas",
    moreInfoTwoDescription: "Mantén a tu mascota sana con nuestros servicios de cuidado. Encuentra veterinarios, vacunas y chequeos de bienestar con proveedores de confianza.",
    moreContactTitle: "Ponte en Contacto",
    moreContactInfo: "Contacta directamente con nuestros socios certificados para conectar con el animal que amas o para encontrar el servicio que estás buscando.",
    moreAdoptionTitle: "Adopción de Mascotas",
    moreAdoptionInfo: "Te ponemos en contacto directo con la persona responsable de la adopción.",
    moreCareTitle: "Cuidado de Mascotas",
    moreCareInfo: "¡Disfruta de servicios premium de cuidado para mantener a tus peluditos sanos, felices y en pleno crecimiento!",
    moreShopTitle: "Tienda de Mascotas",
    moreShopInfo: "Descubre ofertas increíbles en productos de alta calidad para tu peludito en nuestra tienda, ¡asegurando que reciba lo mejor!",
    moreExtraInfo: "*In dui sollicitudin ornare mauris lobortis bibendum felis risus duis mattis penatibus",
    testimonialSection: "Testimonial",
    testimonialTitle: "What they say about us",
}
